import 'package:flutter/material.dart';
import 'package:dio/dio.dart';
import 'dart:convert';
import 'dart:async';


class HttpDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("HttpDemo"),
        elevation: 0.0,
      ),
      body: HttpDemoHome(),
    );
  }
}

class HttpDemoHome extends StatefulWidget {
  

  _HttpDemoHomeState createState() => _HttpDemoHomeState();
}

class _HttpDemoHomeState extends State<HttpDemoHome> {
 
  @override
  void initState() {
   
    super.initState();
    fetchPost();
  }
  List<Posts> data = null;
  void fetchPost () async{
    
     try{
      Dio dio = new Dio();
      Response  response = await dio.get("https://resources.ninghao.net/demo/posts.json");
      String res = response.toString();
      debugPrint(response.data.toString());
      
          Autogenerated autogenerated = new Autogenerated(posts: data);
          Autogenerated.fromJson(json.decode(res));
           
           debugPrint(data.toString());
        }catch (e){
             //print(e);
           }
          
        }
      
        @override
        Widget build(BuildContext context) {
          return Container(
            // child: Text(data[1].title.toString()),
          );
        }
      }
      
      
      class Autogenerated {
        List<Posts> posts;
      
        Autogenerated({this.posts});
      
        Autogenerated.fromJson(Map<String, dynamic> json) {
          if (json['posts'] != null) {
            posts = new List<Posts>();
            json['posts'].forEach((v) {
              posts.add(new Posts.fromJson(v));
            });
          }
        }
      
        Map<String, dynamic> toJson() {
          final Map<String, dynamic> data = new Map<String, dynamic>();
          if (this.posts != null) {
            data['posts'] = this.posts.map((v) => v.toJson()).toList();
          }
          return data;
        }
      
        

 
}

class Posts {
  int id;
  String title;
  String author;
  String description;
  String imageUrl;

  Posts({this.id, this.title, this.author, this.description, this.imageUrl});

  Posts.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    title = json['title'];
    author = json['author'];
    description = json['description'];
    imageUrl = json['imageUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['title'] = this.title;
    data['author'] = this.author;
    data['description'] = this.description;
    data['imageUrl'] = this.imageUrl;
    return data;
  }
}